import type { ExpandableCategoryData } from './ExpandableProgressCategory';

/**
 * Mock data for expandable progress categories
 * Matches the structure shown in the Finance, General Education, and Music screenshots
 */

export const mockExpandableCategories: ExpandableCategoryData[] = [
  // General Education (GE) - Blue
  {
    name: 'General Education',
    totalCredits: 39,
    percentComplete: 0.81,
    color: '#2196f3',
    completed: 31.5,
    inProgress: 3,
    planned: 0,
    remaining: 4.5,
    requirements: [
      {
        id: 'ge-1',
        title: 'American Heritage',
        description: 'Complete 1 of 7 options',
        progress: 1,
        total: 1,
        status: 'completed',
        courses: [
          {
            id: 'ge-1-1',
            code: 'AMHER 201',
            title: 'American Heritage',
            credits: 3,
            status: 'completed',
            term: 'Fall 2023',
          },
        ],
      },
      {
        id: 'ge-2',
        title: 'Global and Cultural Awareness',
        description: 'Complete 1 of 6 options',
        progress: 1,
        total: 1,
        status: 'completed',
        courses: [
          {
            id: 'ge-2-1',
            code: 'GLOB 210',
            title: 'Global Studies',
            credits: 3,
            status: 'completed',
            term: 'Winter 2024',
          },
        ],
      },
      {
        id: 'ge-3',
        title: 'First Year Writing',
        description: 'Complete 2 requirements',
        progress: 2,
        total: 2,
        status: 'completed',
        courses: [
          {
            id: 'ge-3-1',
            code: 'WRTG 150',
            title: 'Writing & Rhetoric',
            credits: 3,
            status: 'completed',
            term: 'Fall 2023',
          },
          {
            id: 'ge-3-2',
            code: 'ENGL 316',
            title: 'Technical Writing',
            credits: 3,
            status: 'completed',
            term: 'Winter 2024',
          },
        ],
      },
      {
        id: 'ge-4',
        title: 'Quantitative Reasoning',
        description: 'Complete 4 credits',
        progress: 4,
        total: 4,
        status: 'completed',
        courses: [
          {
            id: 'ge-4-1',
            code: 'MATH 112',
            title: 'Calculus I',
            credits: 4,
            status: 'completed',
            term: 'Fall 2023',
          },
        ],
      },
      {
        id: 'ge-5',
        title: 'Life Sciences',
        description: 'Complete 3 credits',
        progress: 3,
        total: 3,
        status: 'in-progress',
        courses: [
          {
            id: 'ge-5-1',
            code: 'BIO 100',
            title: 'Intro to Biology',
            credits: 3,
            status: 'in-progress',
            term: 'Fall 2025',
          },
        ],
      },
      {
        id: 'ge-6',
        title: 'Physical Sciences',
        description: 'Complete 3 credits',
        progress: 0,
        total: 3,
        status: 'remaining',
        courses: [
          {
            id: 'ge-6-1',
            code: 'CHEM 105',
            title: 'General Chemistry',
            credits: 3,
            status: 'planned',
            term: 'Fall 2026',
          },
        ],
      },
      {
        id: 'ge-7',
        title: 'Humanities',
        description: 'Complete 3 credits',
        progress: 3,
        total: 3,
        status: 'completed',
        courses: [
          {
            id: 'ge-7-1',
            code: 'PHIL 220',
            title: 'Ethics',
            credits: 3,
            status: 'completed',
            term: 'Winter 2025',
          },
        ],
      },
      {
        id: 'ge-8',
        title: 'Social Science',
        description: 'Complete 3 credits',
        progress: 3,
        total: 3,
        status: 'completed',
        courses: [
          {
            id: 'ge-8-1',
            code: 'ECON 110',
            title: 'Principles of Economics',
            credits: 3,
            status: 'completed',
            term: 'Winter 2026',
          },
        ],
      },
    ],
  },

  // Major - Green
  {
    name: 'Major',
    totalCredits: 64,
    percentComplete: 0.63,
    color: 'var(--primary)',
    completed: 40,
    inProgress: 6,
    planned: 6,
    remaining: 12,
    requirements: [
      {
        id: 'major-1',
        title: 'Core Foundation Courses',
        description: 'Complete 4 foundational courses',
        progress: 4,
        total: 4,
        status: 'completed',
        courses: [
          {
            id: 'major-1-1',
            code: 'CS 101',
            title: 'Intro to Programming',
            credits: 3,
            status: 'completed',
            term: 'Fall 2023',
          },
          {
            id: 'major-1-2',
            code: 'CS 142',
            title: 'Data Structures',
            credits: 3,
            status: 'completed',
            term: 'Winter 2024',
          },
          {
            id: 'major-1-3',
            code: 'CS 235',
            title: 'Algorithms',
            credits: 3,
            status: 'completed',
            term: 'Fall 2024',
          },
          {
            id: 'major-1-4',
            code: 'CS 236',
            title: 'Discrete Math',
            credits: 3,
            status: 'completed',
            term: 'Fall 2024',
          },
        ],
      },
      {
        id: 'major-2',
        title: 'Systems & Architecture',
        description: 'Complete 3 courses',
        progress: 2,
        total: 3,
        status: 'in-progress',
        courses: [
          {
            id: 'major-2-1',
            code: 'CS 240',
            title: 'Advanced Programming',
            credits: 3,
            status: 'completed',
            term: 'Winter 2025',
          },
          {
            id: 'major-2-2',
            code: 'CS 324',
            title: 'Systems Programming',
            credits: 3,
            status: 'in-progress',
            term: 'Fall 2025',
          },
          {
            id: 'major-2-3',
            code: 'CS 345',
            title: 'Operating Systems',
            credits: 3,
            status: 'planned',
            term: 'Winter 2026',
          },
        ],
      },
      {
        id: 'major-3',
        title: 'Software Engineering',
        description: 'Complete 2 courses',
        progress: 0,
        total: 2,
        status: 'remaining',
        courses: [
          {
            id: 'major-3-1',
            code: 'CS 340',
            title: 'Software Engineering',
            credits: 3,
            status: 'planned',
            term: 'Winter 2026',
          },
          {
            id: 'major-3-2',
            code: 'CS 490',
            title: 'Senior Project',
            credits: 3,
            status: 'remaining',
            term: 'Winter 2027',
          },
        ],
      },
      {
        id: 'major-4',
        title: 'Elective Concentration',
        description: 'Complete 4 elective courses',
        progress: 2,
        total: 4,
        status: 'in-progress',
        courses: [
          {
            id: 'major-4-1',
            code: 'CS 312',
            title: 'Algorithm Design',
            credits: 3,
            status: 'completed',
            term: 'Fall 2025',
          },
          {
            id: 'major-4-2',
            code: 'CS 355',
            title: 'Security',
            credits: 3,
            status: 'in-progress',
            term: 'Winter 2026',
          },
          {
            id: 'major-4-3',
            code: 'CS 450',
            title: 'Machine Learning',
            credits: 3,
            status: 'planned',
            term: 'Fall 2026',
          },
          {
            id: 'major-4-4',
            code: 'CS 460',
            title: 'Database Systems',
            credits: 3,
            status: 'remaining',
            term: 'Fall 2026',
          },
        ],
      },
    ],
  },

  // Religion - Indigo
  {
    name: 'Religion',
    totalCredits: 14,
    percentComplete: 0.86,
    color: '#5E35B1',
    completed: 12,
    inProgress: 0,
    planned: 2,
    remaining: 0,
    requirements: [
      {
        id: 'rel-1',
        title: 'Foundation Scriptures',
        description: 'Complete 4 foundational courses',
        progress: 4,
        total: 4,
        status: 'completed',
        courses: [
          {
            id: 'rel-1-1',
            code: 'REL 121',
            title: 'Foundations',
            credits: 2,
            status: 'completed',
            term: 'Fall 2023',
          },
          {
            id: 'rel-1-2',
            code: 'REL 122',
            title: 'Jesus Christ',
            credits: 2,
            status: 'completed',
            term: 'Winter 2024',
          },
          {
            id: 'rel-1-3',
            code: 'REL 225',
            title: 'Book of Mormon',
            credits: 2,
            status: 'completed',
            term: 'Winter 2025',
          },
          {
            id: 'rel-1-4',
            code: 'REL 333',
            title: 'Doctrine & Covenants',
            credits: 2,
            status: 'completed',
            term: 'Winter 2026',
          },
        ],
      },
      {
        id: 'rel-2',
        title: 'Advanced Study',
        description: 'Complete 3 advanced courses',
        progress: 2,
        total: 3,
        status: 'in-progress',
        courses: [
          {
            id: 'rel-2-1',
            code: 'REL 250',
            title: 'Church History',
            credits: 2,
            status: 'completed',
            term: 'Fall 2024',
          },
          {
            id: 'rel-2-2',
            code: 'REL 341',
            title: 'Pearl of Great Price',
            credits: 2,
            status: 'planned',
            term: 'Winter 2027',
          },
          {
            id: 'rel-2-3',
            code: 'REL 370',
            title: 'Teachings of Living Prophets',
            credits: 2,
            status: 'remaining',
            term: 'TBD',
          },
        ],
      },
    ],
  },

  // Electives - Magenta
  {
    name: 'Electives',
    totalCredits: 10.16,
    percentComplete: 1.0,
    color: '#9C27B0',
    completed: 10.16,
    inProgress: 0,
    planned: 0,
    remaining: 0,
    requirements: [
      {
        id: 'elective-1',
        title: 'Free Electives',
        description: 'Complete 10.16 credits of electives',
        progress: 10.16,
        total: 10.16,
        status: 'completed',
        courses: [
          {
            id: 'elective-1-1',
            code: 'MUS 101',
            title: 'Music Appreciation',
            credits: 2,
            status: 'completed',
            term: 'Fall 2024',
          },
          {
            id: 'elective-1-2',
            code: 'ART 101',
            title: 'Art History',
            credits: 2,
            status: 'completed',
            term: 'Fall 2025',
          },
          {
            id: 'elective-1-3',
            code: 'PE 150',
            title: 'Fitness',
            credits: 0.5,
            status: 'completed',
            term: 'Winter 2025',
          },
          {
            id: 'elective-1-4',
            code: 'PE 151',
            title: 'Aerobics',
            credits: 0.5,
            status: 'completed',
            term: 'Winter 2026',
          },
          {
            id: 'elective-1-5',
            code: 'DANC 180',
            title: 'Social Dance',
            credits: 1.66,
            status: 'completed',
            term: 'Winter 2027',
          },
          {
            id: 'elective-1-6',
            code: 'COMM 101',
            title: 'Public Speaking',
            credits: 3,
            status: 'completed',
            term: 'Fall 2026',
          },
          {
            id: 'elective-1-7',
            code: 'GEOG 120',
            title: 'World Geography',
            credits: 0.5,
            status: 'completed',
            term: 'Fall 2024',
          },
        ],
      },
    ],
  },
];

export default mockExpandableCategories;
