import type { ProgressCategory } from './types';

// Mock data matching ACTUAL Finance program requirements
export const mockFinanceProgress: ProgressCategory = {
  name: 'Finance',
  color: 'var(--primary)', // Green
  totalCredits: 64,
  percentComplete: 68,
  completed: 42,
  inProgress: 9,
  planned: 10,
  remaining: 3,
  requirements: [
    {
      id: 1,
      title: 'Course Prerequisites',
      description: 'Complete 2 Requirements',
      progress: 2,
      total: 2,
      status: 'completed',
      completed: 2,
      inProgress: 0,
      planned: 0,
      remaining: 0,
      subrequirements: [
        {
          id: '1.1',
          title: 'Requirement 1.1',
          description: 'Complete 2 Courses',
          progress: 2,
          total: 2,
          status: 'completed',
          completed: 2,
          inProgress: 0,
          planned: 0,
          remaining: 0,
          courses: [
            { id: '1.1-1', code: 'ACC 200', title: 'Principles of Accounting', credits: 3, status: 'completed' },
            { id: '1.1-2', code: 'FIN 201', title: 'Principles of Finance', credits: 3, status: 'completed' },
          ],
        },
        {
          id: '1.2',
          title: 'Requirement 1.2',
          description: 'Complete 3 hours',
          progress: 1,
          total: 1,
          status: 'completed',
          completed: 1,
          inProgress: 0,
          planned: 0,
          remaining: 0,
          courses: [
            { id: '1.2-1', code: 'ACC 310', title: 'Principles of Acctg 2', credits: 3, status: 'completed' },
          ],
        },
      ],
    },
    {
      id: 2,
      title: 'Required Courses',
      description: 'Complete 3 Courses',
      progress: 3,
      total: 3,
      status: 'completed',
      completed: 3,
      inProgress: 0,
      planned: 0,
      remaining: 0,
      courses: [
        { id: '2-1', code: 'ECON 110', title: 'Econ Principles & Problems', credits: 3, status: 'completed' },
        { id: '2-2', code: 'IS 110', title: 'Spreadsheets & Bus Analysis', credits: 1, status: 'completed' },
        { id: '2-3', code: 'STAT 121', title: 'Intro to Stat Data Analysis', credits: 3, status: 'completed' },
      ],
    },
    {
      id: 3,
      title: 'Core Finance Courses',
      description: 'Complete 6 Courses',
      progress: 4,
      total: 6,
      status: 'in-progress',
      completed: 3,
      inProgress: 1,
      planned: 2,
      remaining: 0,
      courses: [
        { id: '3-1', code: 'ACC 310', title: 'Principles of Acctg 2', credits: 3, status: 'completed', term: 'Fall 2023' },
        { id: '3-2', code: 'FIN 326', title: 'Professional Development', credits: 2, status: 'completed', term: 'Winter 2024' },
        { id: '3-3', code: 'FIN 400', title: 'Analytical Methods in Finance', credits: 3, status: 'completed', term: 'Fall 2024' },
        { id: '3-4', code: 'FIN 401', title: 'Adv Financial Management', credits: 3, status: 'in-progress', term: 'Winter 2025' },
        { id: '3-5', code: 'FIN 410', title: 'Investments', credits: 3, status: 'planned', term: 'Fall 2025' },
        { id: '3-6', code: 'FIN 453', title: 'Money, Banking, & Business', credits: 3, status: 'planned' }, // No term - shows TBD
      ],
    },
    {
      id: 4,
      title: 'Business Foundation Courses',
      description: 'Complete 6 Courses',
      progress: 6,
      total: 6,
      status: 'completed',
      completed: 6,
      inProgress: 0,
      planned: 0,
      remaining: 0,
      courses: [
        { id: '4-1', code: 'ACC 241', title: 'Business Law', credits: 3, status: 'completed' },
        { id: '4-2', code: 'GSCM 201', title: 'Intro Global Supply Chain Mgt', credits: 1.5, status: 'completed' },
        { id: '4-3', code: 'GSCM 211', title: 'Intro to GSCM International', credits: 1.5, status: 'completed' },
        { id: '4-4', code: 'IS 201', title: 'Intro to Mgt Info Systems', credits: 3, status: 'completed' },
        { id: '4-5', code: 'M COM 320', title: 'Management Communication', credits: 3, status: 'completed' },
        { id: '4-6', code: 'MKTG 201', title: 'Marketing Management', credits: 3, status: 'completed' },
      ],
    },
    {
      id: 5,
      title: 'Advanced Business Courses',
      description: 'Complete 3 Courses',
      progress: 2,
      total: 3,
      status: 'in-progress',
      completed: 1,
      inProgress: 1,
      planned: 1,
      remaining: 0,
      courses: [
        { id: '5-1', code: 'HRM 391', title: 'Organizational Effectiveness', credits: 3, status: 'completed', term: 'Fall 2024' },
        { id: '5-2', code: 'MSB 390', title: 'Ethics for Management', credits: 3, status: 'in-progress', term: 'Winter 2025' },
        { id: '5-3', code: 'STRAT 392', title: 'Strategy and Economics', credits: 3, status: 'planned', term: 'Spring 2025' },
      ],
    },
    {
      id: 6,
      title: 'Finance Electives',
      description: 'Complete 3 of 19 Courses',
      progress: 2,
      total: 3,
      status: 'in-progress',
      completed: 1,
      inProgress: 1,
      planned: 1,
      remaining: 0,
      courses: [
        { id: '6-1', code: 'FIN 409', title: 'Modeling and Valuation', credits: 3, status: 'completed' },
        { id: '6-2', code: 'FIN 411', title: 'Financial Derivatives', credits: 3, status: 'in-progress' },
        { id: '6-3', code: 'FIN 420', title: 'Fixed Income Asset Management', credits: 3, status: 'planned' },
      ],
    },
    {
      id: 7,
      title: 'Professional Development',
      description: 'Complete 1 of 4 Courses',
      progress: 1,
      total: 1,
      status: 'completed',
      completed: 1,
      inProgress: 0,
      planned: 0,
      remaining: 0,
      courses: [
        { id: '7-1', code: 'MSB 380', title: 'Executive Lectures', credits: 1, status: 'completed' },
      ],
    },
    {
      id: 8,
      title: 'Program Completion',
      description: 'Complete Exit Survey',
      progress: 0,
      total: 1,
      status: 'not-started',
      completed: 0,
      inProgress: 0,
      planned: 1,
      remaining: 0,
      courses: [
        { id: '8-1', code: 'Exit Survey', title: 'Marriott School Exit Survey', credits: 0, status: 'planned' },
      ],
    },
  ],
};

// Mock data for General Education category
export const mockGEProgress: ProgressCategory = {
  name: 'General Education',
  color: '#2196f3', // Blue
  totalCredits: 39,
  percentComplete: 81,
  completed: 32,
  inProgress: 3,
  planned: 4,
  remaining: 0,
  requirements: [
    {
      id: 1,
      title: 'Arts & Letters',
      description: 'Complete 9 credit hours',
      progress: 9,
      total: 9,
      status: 'completed',
      completed: 3,
      inProgress: 0,
      planned: 0,
      remaining: 0,
      courses: [
        { id: 'ge1-1', code: 'ENG 251', title: 'Introduction to Literature', credits: 3, status: 'completed' },
        { id: 'ge1-2', code: 'PHIL 201', title: 'Ethics and Values', credits: 3, status: 'completed' },
        { id: 'ge1-3', code: 'MUSC 101', title: 'Music Appreciation', credits: 3, status: 'completed' },
      ],
    },
    {
      id: 2,
      title: 'Social Sciences',
      description: 'Complete 9 credit hours',
      progress: 9,
      total: 9,
      status: 'completed',
      completed: 3,
      inProgress: 0,
      planned: 0,
      remaining: 0,
      courses: [
        { id: 'ge2-1', code: 'PSYCH 111', title: 'General Psychology', credits: 3, status: 'completed' },
        { id: 'ge2-2', code: 'SOC 101', title: 'Introduction to Sociology', credits: 3, status: 'completed' },
        { id: 'ge2-3', code: 'POLI 110', title: 'American Government', credits: 3, status: 'completed' },
      ],
    },
    {
      id: 3,
      title: 'Physical Sciences',
      description: 'Complete 6 credit hours',
      progress: 4,
      total: 6,
      status: 'in-progress',
      completed: 1,
      inProgress: 1,
      planned: 0,
      remaining: 0,
      courses: [
        { id: 'ge3-1', code: 'PHYS 121', title: 'General Physics', credits: 3, status: 'completed' },
        { id: 'ge3-2', code: 'CHEM 105', title: 'General Chemistry', credits: 3, status: 'in-progress' },
      ],
    },
    {
      id: 4,
      title: 'Life Sciences',
      description: 'Complete 3 credit hours',
      progress: 3,
      total: 3,
      status: 'completed',
      completed: 1,
      inProgress: 0,
      planned: 0,
      remaining: 0,
      courses: [
        { id: 'ge4-1', code: 'BIO 100', title: 'Principles of Biology', credits: 3, status: 'completed' },
      ],
    },
    {
      id: 5,
      title: 'Civilization',
      description: 'Complete 6 credit hours',
      progress: 6,
      total: 6,
      status: 'completed',
      completed: 2,
      inProgress: 0,
      planned: 0,
      remaining: 0,
      courses: [
        { id: 'ge5-1', code: 'HIST 201', title: 'Western Civilization I', credits: 3, status: 'completed' },
        { id: 'ge5-2', code: 'HIST 202', title: 'Western Civilization II', credits: 3, status: 'completed' },
      ],
    },
    {
      id: 6,
      title: 'Foundations',
      description: 'Complete 6 credit hours',
      progress: 1,
      total: 6,
      status: 'in-progress',
      completed: 0,
      inProgress: 1,
      planned: 1,
      remaining: 0,
      courses: [
        { id: 'ge6-1', code: 'WRTG 150', title: 'Writing & Rhetoric', credits: 3, status: 'in-progress', term: 'Winter 2025' },
        { id: 'ge6-2', code: 'MATH 112', title: 'Calculus I', credits: 3, status: 'planned', term: 'Summer 2025' },
      ],
    },
  ],
};

// Mock data for Religion category
export const mockReligionProgress: ProgressCategory = {
  name: 'Religion',
  color: '#5E35B1', // Indigo
  totalCredits: 14,
  percentComplete: 86,
  completed: 12,
  inProgress: 2,
  planned: 0,
  remaining: 0,
  requirements: [
    {
      id: 1,
      title: 'Book of Mormon',
      description: 'Complete 2 courses',
      progress: 2,
      total: 2,
      status: 'completed',
      completed: 2,
      inProgress: 0,
      planned: 0,
      remaining: 0,
      courses: [
        { id: 'rel1-1', code: 'REL A 121', title: 'Book of Mormon I', credits: 2, status: 'completed' },
        { id: 'rel1-2', code: 'REL A 122', title: 'Book of Mormon II', credits: 2, status: 'completed' },
      ],
    },
    {
      id: 2,
      title: 'New Testament',
      description: 'Complete 2 courses',
      progress: 2,
      total: 2,
      status: 'completed',
      completed: 2,
      inProgress: 0,
      planned: 0,
      remaining: 0,
      courses: [
        { id: 'rel2-1', code: 'REL C 211', title: 'New Testament I', credits: 2, status: 'completed' },
        { id: 'rel2-2', code: 'REL C 212', title: 'New Testament II', credits: 2, status: 'completed' },
      ],
    },
    {
      id: 3,
      title: 'Old Testament',
      description: 'Complete 2 courses',
      progress: 2,
      total: 2,
      status: 'completed',
      completed: 2,
      inProgress: 0,
      planned: 0,
      remaining: 0,
      courses: [
        { id: 'rel3-1', code: 'REL C 225', title: 'Old Testament I', credits: 2, status: 'completed' },
        { id: 'rel3-2', code: 'REL C 226', title: 'Old Testament II', credits: 2, status: 'completed' },
      ],
    },
    {
      id: 4,
      title: 'Doctrine & Covenants',
      description: 'Complete 2 courses',
      progress: 1,
      total: 2,
      status: 'in-progress',
      completed: 0,
      inProgress: 1,
      planned: 1,
      remaining: 0,
      courses: [
        { id: 'rel4-1', code: 'REL C 324', title: 'Doctrine & Covenants I', credits: 2, status: 'in-progress', term: 'Winter 2025' },
        { id: 'rel4-2', code: 'REL C 325', title: 'Doctrine & Covenants II', credits: 2, status: 'planned', term: 'Fall 2025' },
      ],
    },
  ],
};

// Mock data for Electives category
export const mockElectivesProgress: ProgressCategory = {
  name: 'Electives',
  color: '#9C27B0', // Magenta
  totalCredits: 10.16,
  percentComplete: 100,
  completed: 10.16,
  inProgress: 0,
  planned: 0,
  remaining: 0,
  requirements: [
    {
      id: 1,
      title: 'Free Electives',
      description: 'Complete 10.16 credit hours',
      progress: 10.16,
      total: 10.16,
      status: 'completed',
      completed: 4,
      inProgress: 0,
      planned: 0,
      remaining: 0,
      courses: [
        { id: 'elec1-1', code: 'DANC 180', title: 'Social Dance', credits: 1, status: 'completed' },
        { id: 'elec1-2', code: 'PE 160', title: 'Fitness for Life', credits: 2, status: 'completed' },
        { id: 'elec1-3', code: 'CS 105', title: 'Introduction to Programming', credits: 3, status: 'completed' },
        { id: 'elec1-4', code: 'GEOG 120', title: 'World Regional Geography', credits: 4.16, status: 'completed' },
      ],
    },
  ],
};

// Array of all mock categories for easy iteration
export const mockAllCategories: ProgressCategory[] = [
  mockFinanceProgress,
  mockGEProgress,
  mockReligionProgress,
  mockElectivesProgress,
];

// Mock data for Minor category
export const mockMinorProgress: ProgressCategory = {
  name: 'Minor',
  color: '#003D82', // Medium blue - darker than bright but lighter than navy
  totalCredits: 24,
  percentComplete: 45,
  completed: 11,
  inProgress: 3,
  planned: 6,
  remaining: 4,
  requirements: [
    {
      id: 1,
      title: 'Core Requirements',
      description: 'Complete 4 courses',
      progress: 2,
      total: 4,
      status: 'in-progress' as const,
      completed: 2,
      inProgress: 1,
      planned: 1,
      remaining: 0,
      courses: [
        { id: 'minor1-1', code: 'MINOR 201', title: 'Introduction to Minor', credits: 3, status: 'completed', term: 'Fall 2023' },
        { id: 'minor1-2', code: 'MINOR 301', title: 'Intermediate Minor', credits: 3, status: 'completed', term: 'Winter 2024' },
        { id: 'minor1-3', code: 'MINOR 401', title: 'Advanced Minor', credits: 3, status: 'in-progress', term: 'Winter 2025' },
        { id: 'minor1-4', code: 'MINOR 450', title: 'Minor Capstone', credits: 3, status: 'planned', term: 'Fall 2025' },
      ],
    },
    {
      id: 2,
      title: 'Elective Requirements',
      description: 'Complete 2 courses',
      progress: 1,
      total: 2,
      status: 'in-progress' as const,
      completed: 1,
      inProgress: 0,
      planned: 1,
      remaining: 0,
      courses: [
        { id: 'minor2-1', code: 'MINOR 320', title: 'Minor Elective I', credits: 3, status: 'completed', term: 'Fall 2024' },
        { id: 'minor2-2', code: 'MINOR 330', title: 'Minor Elective II', credits: 3, status: 'planned' },
      ],
    },
  ],
};

// Array of all mock categories including Minor (for design preview and grad-plan)
export const mockAllCategoriesWithMinor: ProgressCategory[] = [
  mockFinanceProgress,
  mockMinorProgress,
  mockGEProgress,
  mockReligionProgress,
  mockElectivesProgress,
];
