-- Migration: Create Authorization Infrastructure Tables
-- Phase 1b: New tables for database-first authorization

-- =============================================================================
-- 1. user_roles: Canonical role assignments (single source of truth)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('student', 'advisor', 'university_admin', 'super_admin')),
  university_id BIGINT REFERENCES public.university(id),
  granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  granted_by UUID REFERENCES auth.users(id),
  UNIQUE(user_id, role)
);

COMMENT ON TABLE public.user_roles IS 'Canonical role assignments - single source of truth for user roles';
COMMENT ON COLUMN public.user_roles.role IS 'Role name: student, advisor, university_admin, or super_admin';
COMMENT ON COLUMN public.user_roles.university_id IS 'University context for the role (required for most roles)';
COMMENT ON COLUMN public.user_roles.granted_by IS 'User who granted this role (NULL for self-registration)';

-- Enable RLS on user_roles
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can SELECT their own roles only
CREATE POLICY "Users can view own roles"
  ON public.user_roles
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- No INSERT/UPDATE/DELETE policies for clients - only service_role can modify

-- =============================================================================
-- 2. advisor_students: Explicit per-student advisor grants
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.advisor_students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  student_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  granted_by UUID REFERENCES auth.users(id),
  UNIQUE(advisor_id, student_id)
);

COMMENT ON TABLE public.advisor_students IS 'Explicit advisor-to-student relationship grants';
COMMENT ON COLUMN public.advisor_students.granted_by IS 'User who created this relationship (typically admin or system)';

-- Enable RLS on advisor_students
ALTER TABLE public.advisor_students ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Advisors and students can view rows where they're either party
CREATE POLICY "View advisor-student relationships"
  ON public.advisor_students
  FOR SELECT
  TO authenticated
  USING (
    advisor_id = auth.uid() OR
    student_id = auth.uid()
  );

-- No INSERT/UPDATE/DELETE policies for clients - only service_role can modify

-- =============================================================================
-- 3. advisor_programs: Advisor-to-program relationship
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.advisor_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  program_id BIGINT NOT NULL REFERENCES public.program(id) ON DELETE CASCADE,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  granted_by UUID REFERENCES auth.users(id),
  UNIQUE(advisor_id, program_id)
);

COMMENT ON TABLE public.advisor_programs IS 'Advisor-to-program relationship (replaces advisors.programs array)';
COMMENT ON COLUMN public.advisor_programs.granted_by IS 'User who granted this program access (typically admin)';

-- Enable RLS on advisor_programs
ALTER TABLE public.advisor_programs ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Advisors can view their own program assignments
CREATE POLICY "Advisors view own programs"
  ON public.advisor_programs
  FOR SELECT
  TO authenticated
  USING (advisor_id = auth.uid());

-- No INSERT/UPDATE/DELETE policies for clients - only service_role can modify

-- =============================================================================
-- 4. advisor_requests: User-initiated advisor role requests
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.advisor_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  university_id BIGINT NOT NULL REFERENCES public.university(id),
  requested_programs BIGINT[] DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'denied')),
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  decided_at TIMESTAMPTZ,
  decided_by UUID REFERENCES auth.users(id),
  notes TEXT
);

COMMENT ON TABLE public.advisor_requests IS 'User-initiated requests for advisor role';
COMMENT ON COLUMN public.advisor_requests.requested_programs IS 'Array of program IDs the user wants to advise';
COMMENT ON COLUMN public.advisor_requests.status IS 'Request status: pending, approved, or denied';
COMMENT ON COLUMN public.advisor_requests.decided_by IS 'Admin who approved/denied the request';
COMMENT ON COLUMN public.advisor_requests.notes IS 'Admin notes about the decision';

-- Enable RLS on advisor_requests
ALTER TABLE public.advisor_requests ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view their own requests
CREATE POLICY "View own advisor requests"
  ON public.advisor_requests
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- RLS Policy: Users can insert requests for themselves (with constraints)
CREATE POLICY "Insert own advisor request"
  ON public.advisor_requests
  FOR INSERT
  TO authenticated
  WITH CHECK (
    user_id = auth.uid() AND
    status = 'pending'
  );

-- No UPDATE/DELETE policies for clients - only service_role can modify status

-- =============================================================================
-- Create indexes for performance
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON public.user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON public.user_roles(role);
CREATE INDEX IF NOT EXISTS idx_advisor_students_advisor_id ON public.advisor_students(advisor_id);
CREATE INDEX IF NOT EXISTS idx_advisor_students_student_id ON public.advisor_students(student_id);
CREATE INDEX IF NOT EXISTS idx_advisor_programs_advisor_id ON public.advisor_programs(advisor_id);
CREATE INDEX IF NOT EXISTS idx_advisor_programs_program_id ON public.advisor_programs(program_id);
CREATE INDEX IF NOT EXISTS idx_advisor_requests_user_id ON public.advisor_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_advisor_requests_status ON public.advisor_requests(status);
